language: node_js
node_js:
  - stable
script:
  - bash ./deploy.sh
env:
  global:
    - ENCRYPTION_LABEL: "182890a63101"
    - COMMIT_AUTHOR_EMAIL: "github@greggman.com"

before_install: npm install -g grunt-cli
